### ISSUE TITLE
Unhandled Exception when utility is run from Release directory

### ISSUE THREAD

**Issue by jtipeetoes** [JimDaly/CRMJSWebAPIServiceUtil#21]
The following error occurs
CRMJSWebAPIServiceUtil has stopped working... 
A problem caused the program to stop working correctly. Please close the program. 

Steps to recreate:
1. Download the utility from github
2. Unblock the zip file via properties menu 
3. Extract all zip file contents
4. Run the the utility from the resulting 'Release' directory (run as Administrator)
5. Hit the 'Login to CRM' button on the utility
6. Entering the following into the dialog 

Table

![image](https://cloud.githubusercontent.com/assets/1518694/22348679/a3e7ae1a-e3da-11e6-9f65-342ce6014dd7.png)

Error
![image](https://cloud.githubusercontent.com/assets/1518694/22348625/6e5d4bb0-e3da-11e6-88d8-8646d492ea2a.png)

Environment Details
![image](https://cloud.githubusercontent.com/assets/1518694/22348640/81b67d9e-e3da-11e6-8fca-c9b6bc431f06.png)

**Comment by JimDaly** [comment]
Thanks for reporting this. Quick response: I notice from your screenshot that you appear to have IFD enabled for your on-premises environment. The URL in the about window is `<org>.elitecorp.com` rather than `<server>/<org name>`.  Please forgive the stupid question, (_I don't have an IFD enabled test environment_) but can you not also access the server using '`http://<server>/<org name>`'?  - the regular on-premise manner?

**Comment by jtipeetoes** [comment]
Afraid it’s not IFD - as claims is not configured. I do have two bindings on the website one http:// and one https:// (using a self-signed certificate as it is a development environment). Here at TR (Thomson Reuters) we have a couple of domains in play and this often forces us to further qualify the name of the application server.

In the CRM Deployment manager application the service bindings all point to port 80.
<removed extra information from email thread>

**Comment by JimDaly** [comment]
Applied pull request #23 which I believe will fix this issue.
Please sync and test again. Let me know if it worked and we can close this issue.
