### ISSUE TITLE
Cannot authenticate on an AD FS + IFD environment

### ISSUE THREAD

**Issue by mehmetseckin** [JimDaly/CRMJSWebAPIServiceUtil#4]
Took it for a spin on an IFD-enabled environment with claims-based authentication (AD FS).

The `WhoAmI()` request returns a html document containing a generic error message, and the event viewer had the following logs, seems like it fails to authenticate.

Also, i needed to provide my username in a `domain\username` format, otherwise it keeps giving `401: Unauthorized.`. Although I know this is something to do with Windows Server 2012 R2, this doesn't happen on Windows Server 2012.

```
Fault bucket , type 0
Event Name: CRMmanaged2
Response: Not available
Cab Id: 0

Problem signature:
P1: 8.1.0.359
P2: w3wp
P3: Microsoft.Crm.Application.Pages
P4: UriFormatException
P5: UpdateRedirectingEventArgsNonPathBasedUrlWithoutLiveId
P6: 1D
P7: 
P8: 
P9: 
P10: 

Exception information: 
    Exception type: UriFormatException 
    Exception message: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.UriBuilder..ctor(String uri)
   at Microsoft.Crm.Authentication.Claims.CrmFederatedAuthenticationModule.UpdateRedirectingEventArgsNonPathBasedUrlWithoutLiveId(RedirectLocation redirectLocation, RedirectingToIdentityProviderEventArgs e)
   at Microsoft.Crm.Authentication.Claims.CrmFederatedAuthenticationModule.SendToIdentityProvider(RedirectLocation redirectLocation)
   at Microsoft.Crm.Authentication.Claims.CrmFederatedAuthenticationModule.RedirectToIdentityProvider(String uniqueId, String returnUrl, Boolean persist)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)



Request information: 
    Request URL: https://orgname.domain.com:444/api/data/v8.1/WhoAmI() 
    Request path: /api/data/v8.1/WhoAmI() 
    User host address: xxx.xxx.xxx.xxx 
    User:  
    Is authenticated: False 
    Authentication Type:  
    Thread account name: DOMAIN\CRMSERVICE 

Thread information: 
    Thread ID: 229 
    Thread account name: DOMAIN\CRMSERVICE 
    Is impersonating: True 
```

**Comment by JimDaly** [comment]
Just want to make sure: Are you referring to the WPF application or the JS code generated by this application?
If it is the application:
If it isn't too much trouble, can I ask you to try one of the samples under [Web API Samples (C#)](https://msdn.microsoft.com/en-us/library/mt742432.aspx)? These use the same authentication helpers. If you get the same error I can work with the author of those helpers to fix it.

**Comment by mehmetseckin** [comment]
Hello Jim,

Before all, I'm sorry for the mistake, just realized I've opened the issue in the _wrong repository_, this belongs to [CRMWebAPILoginControl](https://github.com/JimDaly/CRMWebAPILoginControl/issues).

I've tried to [run the Web API Basic Operations Sample (C#)](https://msdn.microsoft.com/en-us/library/mt770369.aspx#bkmk_runSample) with the same connection information, but kept getting `401: Unauthorized` responses.

I've simply tried to access `https://orgname.domain.com:444/api/data/v8.1/WhoAmI()` using a browser, and kept getting `401` challenges, even though i provided the right credentials. However, once i've logged in to the CRM application, browsing to the `https://orgname.domain.com:444/api/data/v8.1/WhoAmI()` URL started working.

I went to [the documentation](https://msdn.microsoft.com/en-us/library/mt595798.aspx) to check if there is something specific to do for authenticating to an Internet-facing on-premises deployment; turns out i need to implement OAuth and have my application registered in the Azure Active Directory Authentication Library.

> #### With Microsoft Dynamics CRM Online or internet facing deployments
> 
> When you use the Web API for CRM Online or an on-premises Internet-facing deployment (IFD) you must use OAuth as described in [Connect to Microsoft Dynamics CRM web services using OAuth.](https://msdn.microsoft.com/en-us/library/gg327838.aspx)
> 
> Before you can use OAuth authentication to connect with the CRM web services, your application must first be registered with Microsoft Azure Active Directory. Azure Active Directory is used to verify that your application is permitted access to the business data stored in a CRM tenant.

Therefore I'm closing this issue, thank you very much for pointing me back to the samples.

**Comment by JimDaly** [comment]
Thanks. I need to update the docs to call out that you must register the app for IFD deployments as well as for CRM Online.
